opensearch-project/dashboards-notifications

- .github/workflows/dashboards-notifications-test-and-build-workflow.yml
Signed-off-by: Chenyang Ji <cyji@amazon.com>
This PR ensures github workflow pass for the `dashboards-notifications` repo. It does the following things:
1. Removes the unused workflows which belong to the original `notifications` repo;
2. Update the `dashboards-notifications-test-and-build-workflow.yml` file to ensure build pass.
https://github.com/opensearch-project/notifications/issues/466
> update github workflow files for dashboards-notifications

- .github/workflows/dashboards-notifications-test-and-build-workflow.yml
> [Backport main] feat: fix CI flow

- .github/workflows/dashboards-notifications-test-and-build-workflow.yml
- release-notes/opensearch-dashboards-notifications.release-notes-2.8.0.0.md
* Fix CI on Node.js v18
Signed-off-by: suzhou <suzhou@amazon.com>
* feat: update release notes
Signed-off-by: suzhou <suzhou@amazon.com>
---------
Signed-off-by: suzhou <suzhou@amazon.com>
(cherry picked from commit 6d576e46c425fb2eef5eca6686ed4957fcb6378e)
> [Backport 2.x] Fix CI on Node.js v18 (#56)

- .eslintrc.js
- opensearch_dashboards.json
- package.json
- public/pages/Main/Main.tsx
- public/plugin.ts
- public/types.ts
Move notification from plugins section into Management section and register which pages does the plugin have to show in management overview page
#48 
> Move notification plugin into management section on left navigation menu

- .cypress/fixtures/test_microsoft_teams_channel.json
- .cypress/integration/channels.spec.js
- cypress.json
- models/interfaces.ts
- public/pages/Channels/__tests__/ChannelSettingsDetails.test.tsx
- public/pages/Channels/__tests__/__snapshots__/ChannelSettingsDetails.test.tsx.snap
- public/pages/Channels/components/details/ChannelSettingsDetails.tsx
- public/pages/CreateChannel/CreateChannel.tsx
- public/pages/CreateChannel/__tests__/CreateChannel.test.tsx
- public/pages/CreateChannel/__tests__/MicrosoftTeamsSettings.test.tsx
- public/pages/CreateChannel/__tests__/__snapshots__/MicrosoftTeamsSettings.test.tsx.snap
- public/pages/CreateChannel/components/MicrosoftTeamsSettings.tsx
- public/pages/Emails/__tests__/EmailSenders.test.tsx
- public/pages/Main/Main.tsx
- public/utils/constants.ts
- test/mocks/mockData.ts
add Microsoft Teams support at front-end
https://github.com/opensearch-project/notifications/issues/585
> add microsoft teams support

- .cypress/fixtures/test_microsoft_teams_channel.json
- .cypress/integration/channels.spec.js
- cypress.json
- models/interfaces.ts
- public/pages/Channels/__tests__/ChannelSettingsDetails.test.tsx
- public/pages/Channels/__tests__/__snapshots__/ChannelSettingsDetails.test.tsx.snap
- public/pages/Channels/components/details/ChannelSettingsDetails.tsx
- public/pages/CreateChannel/CreateChannel.tsx
- public/pages/CreateChannel/__tests__/CreateChannel.test.tsx
- public/pages/CreateChannel/__tests__/MicrosoftTeamsSettings.test.tsx
- public/pages/CreateChannel/__tests__/__snapshots__/MicrosoftTeamsSettings.test.tsx.snap
- public/pages/CreateChannel/components/MicrosoftTeamsSettings.tsx
- public/pages/Main/Main.tsx
- public/utils/constants.ts
- test/mocks/mockData.ts
The backport for #44 failed. Create a backport mannually.
The failure reason is 2 UT from commit 8d514d4970481dc2d1ee6fea90e0a28f8b17e4b0 doesn't exist in 2.x, while our PR modify those 2 UT. To keep consistent with previous settings, I remove these modifications in these 2 UT.
> Manually backport #44, support Microsoft Teams config type

- .cypress/integration/email_senders_and_groups.spec.js
- public/pages/Emails/__tests__/SendersTableControls.test.tsx
- public/pages/Emails/components/forms/CreateSenderForm.tsx
- public/utils/constants.ts
When configuring a SMTP sender, the user is prompted for an "Encryption method" and given a drop-down list to choose from.  The list currently contain "SSL", "TLS" and "None" which is a bit confusing given that TLS is built on deprecated SSL and both refer to the same thing.
In this list, "SSL" actually mean TLS, and "TLS" actually mean StartTLS (aka Opportunistic TLS).
Adjust wording to wake this more obvious.  The new wording match the one used in Thunderbird when configuring connection security.
> Improve wording for TLS-related options

- .github/workflows/dashboards-notifications-test-and-build-workflow.yml
Increase OSD start timeout for windows platform from 400s to 900s
> Increase OSD start timeout for windows platform

- .cypress/fixtures/test_slack_channel.json
- .cypress/integration/channels.spec.js
- public/pages/Channels/__tests__/__snapshots__/ChannelSettingsDetails.test.tsx.snap
- test/mocks/mockData.ts
Integrates with [#814](https://github.com/opensearch-project/notifications/pull/814) in the backend notifications repo
Replaces mock Slack URLs (which wouldn't pass validation tests) with mock Slack URLs (which will pass validation tests)
> Replaced wrongly formatted mock Slack URLs with properly formatted mock Slack URLs

- .github/workflows/dashboards-notifications-test-and-build-workflow-prod-docker-linux.yml
- .github/workflows/dashboards-notifications-test-and-build-workflow.yml
1. Fix timeout issue in windows by increasing requestTimeout to 12000s.
2. Upload opensearch.log for future debug. The log file is about 80kb.
> Fix: CI flow on windows main

- .github/workflows/dashboards-notifications-test-and-build-workflow-prod-docker-linux.yml
- .github/workflows/dashboards-notifications-test-and-build-workflow.yml
* feat: remove useless step
Signed-off-by: SuZhou-Joe <suzhou@amazon.com>
* feat: add opensearch logs
Signed-off-by: SuZhou-Joe <suzhou@amazon.com>
* feat: update
Signed-off-by: SuZhou-Joe <suzhou@amazon.com>
* feat: add more requestTimeout
Signed-off-by: SuZhou-Joe <suzhou@amazon.com>
---------
Signed-off-by: SuZhou-Joe <suzhou@amazon.com>
Co-authored-by: Hailong Cui <ihailong@amazon.com>
(cherry picked from commit 15c0b72ac44919d691dc459fc61d1f6d6983318c)
For more information on following Developer Certificate of Origin and signing off your commits, please check …
> [Backport 2.x] Fix: CI flow on windows main (#145)

- .github/workflows/dashboards-notifications-test-and-build-workflow.yml
In Windows, there is a file lock which makes action/upload-artifact unable to upload opensearch.log.
> Feat: remove opensearch.log introduced from #145

- .github/CODEOWNERS
- MAINTAINERS.md
Update MAINTAINERS and CODEOWNERS
> Update MAINTAINERS and CODEOWNERS

- public/services/NotificationService.ts
- server/routes/configRoutes.ts
In notifications plugin, the response from `/_plugins/_notifications/features` is used to derive the available channels. Since, alerting also requires this information and uses the routes setup in the notification dashboards server to fetch the server features, this PR moves the logic of deriving channels to the server itself. This way we keep single source of truth for the available channels and alerting would the updates for free in future.
Plays role in fixing https://github.com/opensearch-project/alerting-dashboards-plugin/issues/795
For more information on following Developer Certificate of Origin and signing off your commits, please check …
> Moved enrichment of server features to server side

- public/components/MDSEnabledComponent/MDSEnabledComponent.tsx
- public/pages/Channels/Channels.tsx
- public/pages/Emails/components/tables/RecipientGroupsTable.tsx
- public/pages/Emails/components/tables/SESSendersTable.tsx
- public/pages/Emails/components/tables/SendersTable.tsx
* This will fix the error when dataSource is switched from a valid dataSource to invalid dataSource i.e when API returns "Data Source Error", the channels/emails list will be empty
https://github.com/opensearch-project/dashboards-notifications/assets/69919272/24f87b67-aaf3-437a-abcb-b75ae6cf7d75
> handle error state properly when dataSource switches

- public/components/MDSEnabledComponent/MDSEnabledComponent.tsx
- public/pages/Main/Main.tsx
- public/services/NotificationService.ts
This PR fixes the bug in MDS support for Notifications. Changes introduced:
* The issue is getSeverFeatures API should take the dataSourceId to return the response as per the provided dataSource
* getServerFeatures API should be called whenever a component updates to update the states as per the dataSource
* Also, removes some unused import from public/components/MDSEnabledComponent/MDSEnabledComponent.tsx
getSeverFeatures API call to support MDS is fixed
> Bug fixes to support mds in getSeverFeatures API 

- public/application.tsx
- public/pages/Main/Main.tsx
- public/plugin.ts
* This PR adds side navigation changes to notification plugin when feature is enabled
After side nav changes, when feature is enabled
When feature is disabled:
> side navigation changes for notifications

- .github/CODEOWNERS
- MAINTAINERS.md
- public/pages/Channels/__tests__/__snapshots__/DetailsListModal.test.tsx.snap
- public/pages/Channels/__tests__/__snapshots__/DetailsTableModal.test.tsx.snap
* Add riysaxen-amzn as a maintainer to dashboards-notifications repo
> add riysaxen as maintainer

- public/pages/Channels/components/details/ChannelDetails.tsx
Use TopNavControlButtonData for channel test button
Note: All other buttons and the general styling of the page are created wrongly and with custom styling so nothing matches.
> Use TopNavControlButtonData for channel test button

- public/components/MDSEnabledComponent/MDSEnabledComponent.tsx
- public/components/PageHeader/PageHeader.tsx
- public/pages/Emails/EmailSenders.tsx
- public/pages/Main/Main.tsx
- public/plugin.ts
- public/utils/constants.ts
Manual backport
* Persist dataSourceId across applications under new Nav change
Signed-off-by: Riya Saxena <riysaxen@amazon.com>
* fixes with mds
Signed-off-by: Riya Saxena <riysaxen@amazon.com>
* fixes with mds
Signed-off-by: Riya Saxena <riysaxen@amazon.com>
* fix UTs
Signed-off-by: Riya Saxena <riysaxen@amazon.com>
* moved to constants
Signed-off-by: Riya Saxena <riysaxen@amazon.com>
* revert changes in snapshot files
Signed-off-by: Riya Saxena <riysaxen@amazon.com>
---------
Signed-off-by: Riya Saxena <riysaxen@amazon.com>
Co-authored-by: Amardeepsingh Siglani <amardeep7194@gmail.com>
(cherry picked from commit f209c40d3124fb5a52fde7b081684aec4f7fc76f)
By submitting this pull request, I confirm that my …
> [Backport 2.x] Persist dataSourceId across applications under new Nav change (#244)

- .github/workflows/dashboards-notifications-test-and-build-workflow-prod-docker-linux.yml
- .github/workflows/dashboards-notifications-test-and-build-workflow.yml
- public/components/ContentPanel/ContentPanel.tsx
- public/components/__tests__/__snapshots__/ContentPanel.test.tsx.snap
- public/pages/Channels/Channels.tsx
- public/pages/Channels/__tests__/__snapshots__/ChannelControls.test.tsx.snap
- public/pages/Channels/__tests__/__snapshots__/ChannelDetails.test.tsx.snap
- public/pages/Channels/__tests__/__snapshots__/Channels.test.tsx.snap
- public/pages/Channels/components/ChannelControls.tsx
- public/pages/Channels/components/details/ChannelDetails.tsx
- public/pages/CreateChannel/CreateChannel.tsx
- public/pages/CreateChannel/__tests__/__snapshots__/ChannelNamePanel.test.tsx.snap
- public/pages/Emails/CreateRecipientGroup.tsx
- public/pages/Emails/CreateSESSender.tsx
- public/pages/Emails/CreateSender.tsx
- public/pages/Emails/EmailGroups.tsx
- public/pages/Emails/EmailSenders.tsx
- public/pages/Emails/__tests__/__snapshots__/RecipientGroupsTable.test.tsx.snap
- public/pages/Emails/__tests__/__snapshots__/SendersTable.test.tsx.snap
- public/pages/Emails/__tests__/__snapshots__/SendersTableControls.test.tsx.snap
- public/pages/Emails/components/forms/CreateRecipientGroupForm.tsx
- public/pages/Emails/components/forms/CreateSESSenderForm.tsx
- public/pages/Emails/components/forms/CreateSenderForm.tsx
- public/pages/Emails/components/tables/RecipientGroupsTable.tsx
- public/pages/Emails/components/tables/SESSendersTable.tsx
- public/pages/Emails/components/tables/SendersTable.tsx
- public/pages/Emails/components/tables/SendersTableControls.tsx
- public/pages/Main/__tests__/__snapshots__/Main.test.tsx.snap
Addresses the fit and finish UX changes. Changes in this PR include:
- Fills the send test message button in the View Channel page
- Fixes the spacing across the data source to actions buttons in the View Channel page
- Makes all content sections run full width of page
- Removes extra 10px padding in Channels and Email recipient groups page
- Removes bottom border across pages when empty prompt
- Fixes the content to header spacing (16px)
- Fixes active indicator alignment in the View Channel page
- Fixes the section headers so it's wrapped in OuiTitle with size = s
- Fixes spacing for actions across elements from search bar (8px)
Empty Channels Page
Channels Page
Edit Channel Page
Email Senders Page
Create SMTP Sender Page
Create SES Sender Page
Email Recipient Group Page
Edit Recipient …
> Fit and Finish UX Fixes

- .github/workflows/dashboards-notifications-test-and-build-workflow.yml
upload-artifact v4 doesn't allow uploading the same artifact name from multiple jobs. This PR updates the name of artifact that is uploaded so it's os specific.
> Fix CI workflow for windows

- public/pages/Channels/__tests__/__snapshots__/ChannelControls.test.tsx.snap
- public/pages/Channels/__tests__/__snapshots__/Channels.test.tsx.snap
- public/pages/Channels/components/ChannelControls.tsx
- public/pages/Emails/__tests__/__snapshots__/SendersTable.test.tsx.snap
- public/pages/Emails/__tests__/__snapshots__/SendersTableControls.test.tsx.snap
- public/pages/Emails/components/tables/SendersTableControls.tsx
- public/pages/Main/__tests__/__snapshots__/Main.test.tsx.snap
Last changes for the fit and finish UX fixes. The changes in this PR include:
- Separating the table filters
- Adding a default pill to the encryption method dropdown
> Fit and Finish UX Fixes Pt 2.

- .github/workflows/dashboards-notifications-test-and-build-workflow.yml
CI is failing on Cache Cypress step.
```
Error: The template is not valid. .github/workflows/dashboards-notifications-test-and-build-workflow.yml (Line: 173, Col: 16): hashFiles('**/package.json') couldn't finish within 120 seconds.
```
This PR adjusts the name of the hashfile so it's consistent with main
```
OpenSearch-Dashboards/plugins/dashboards-notifications/package.json
```
> Fix cache cypress hashfile path

- .github/workflows/dashboards-notifications-test-and-build-workflow-prod-docker-linux.yml
- .github/workflows/dashboards-notifications-test-and-build-workflow.yml
- public/pages/Emails/components/tables/RecipientGroupsTable.tsx
- public/plugin.ts
Found this typo while using playgrounds. Updated text from `recepient` to `recipient`. 
> Fix typo in recipient

- .github/workflows/dashboards-notifications-test-and-build-workflow-prod-docker-linux.yml
- public/pages/Emails/components/tables/RecipientGroupsTable.tsx
- public/plugin.ts
> [Backport 2.x] Fix typo in recipient (#287)

- public/pages/Main/Main.tsx
- public/plugin.ts
- public/utils/constants.ts
- server/routes/configRoutes.ts
* Bug fix to switch to default datasource instead of local cluster when initial loading
https://github.com/user-attachments/assets/71861be4-3f4f-4cdf-a0cf-9d79bf8b5780
> bug fix to switch to default datasource instead of local cluster when initial loading

- package.json
- yarn.lock
Bump form-data to 4.0.4 version in package.json
https://github.com/opensearch-project/opensearch-build/issues/5693#issuecomment-3378529514
> Bump form-data to 4.0.4 version in package.json
