opensearch-project/dashboards-notifications

release-notes/opensearch-dashboards-notifications.release-notes-2.5.0.0.md
Signed-off-by: Chenyang Ji <cyji@amazon.com>
Drafted 2.5 release notes.
https://github.com/opensearch-project/dashboards-notifications/issues/4
=> create 2.5 release notes

.github/workflows/dashboards-notifications-test-and-build-workflow.yml, opensearch_dashboards.json, package.json
=> Bumped version to 2.6.

release-notes/opensearch-dashboards-notifications.release-notes-2.6.0.0.md
=> Drafted 2.6 release notes.

.github/workflows/dashboards-notifications-test-and-build-workflow.yml
=> [Backport 2.x][Manual]Fix Node.js and Yarn installation in CI #16

.github/workflows/dashboards-notifications-test-and-build-workflow.yml, opensearch_dashboards.json, package.json
=> Bump version to 2.7

release-notes/opensearch-dashboards-notifications.release-notes-2.7.0.0.md
=> Draft release notes for v2.7

.github/CODEOWNERS, MAINTAINERS.md
=> Baseline maintainers and codeowners

MAINTAINERS.md
Updated the MAINTAINERS.md file 
Closes #31 
=> Updating the MAINTAINERS.md file

release-notes/opensearch-dashboards-notifications.release-notes-2.8.0.0.md
=> Draft 2.8 release notes

.github/workflows/dashboards-notifications-test-and-build-workflow.yml, release-notes/opensearch-dashboards-notifications.release-notes-2.8.0.0.md
=> Fix CI on Node.js v18

.github/workflows/dashboards-notifications-test-and-build-workflow.yml, release-notes/opensearch-dashboards-notifications.release-notes-2.8.0.0.md
* Fix CI on Node.js v18
Signed-off-by: suzhou <suzhou@amazon.com>
* feat: update release notes
Signed-off-by: suzhou <suzhou@amazon.com>
---------
Signed-off-by: suzhou <suzhou@amazon.com>
(cherry picked from commit 6d576e46c425fb2eef5eca6686ed4957fcb6378e)
=> [Backport 2.8] Fix CI on Node.js v18 (#56)

LICENSE
Add License file on 2.x branch
#59 
=> Add missing LICENSE file on 2.x branch

release-notes/opensearch-dashboards-notifications.release-notes-2.9.0.0.md
=> Drafted 2.9 release notes.

package.json, yarn.lock
=> fix: CVE of tough-cookie and word-wrap

.cypress/integration/channels.spec.js, .cypress/support/commands.js
=> stabilize cypress test case

.github/workflows/backport.yml
upgrade backport workflow to support autocut failure
=> upgrade backport workflow

.github/workflows/backport.yml
=> Fix backport branch name

.github/workflows/auto-release.yml
Add auto github release workflow
https://github.com/opensearch-project/notifications/issues/615
=> Add auto release workflow

release-notes/opensearch-dashboards-notifications.release-notes-2.10.0.0.md
[Add 2.10 release notes]
https://github.com/opensearch-project/dashboards-notifications/issues/86
=> Add 2.10 release notes.

release-notes/opensearch-dashboards-notifications.release-notes-2.11.0.0.md
[Add 2.11 release notes]
https://github.com/opensearch-project/dashboards-notifications/issues/112
=> Add 2.11 release notes

.github/workflows/dashboards-notifications-test-and-build-workflow-prod-docker-linux.yml, .github/workflows/dashboards-notifications-test-and-build-workflow.yml
Onboard jenkins prod docker images to github actions
#127 
=> Onboard jenkins prod docker images to github actions

.cypress/fixtures/test_chime_channel.json, .cypress/integration/channels.spec.js, public/pages/Channels/__tests__/__snapshots__/ChannelSettingsDetails.test.tsx.snap, public/pages/CreateChannel/__tests__/ChimeSettings.test.tsx, test/mocks/mockData.ts
Continues on [#816](https://github.com/opensearch-project/notifications/pull/816)
[#788](https://github.com/opensearch-project/notifications/issues/788)
=> Replace all wrong Chime urls with correct ones

release-notes/opensearch-dashboards-notifications.release-notes-2.12.0.0.md
Drafted release notes.
https://github.com/opensearch-project/dashboards-notifications/issues/128
=> Drafted release notes.

release-notes/opensearch-dashboards-notifications.release-notes-2.13.0.0.md
=> Added 2.13.0 release notes.

.github/CODEOWNERS, MAINTAINERS.md
=> Add AWSHurneyt as maintainer

opensearch_dashboards.json, public/components/MDSEnabledComponent/MDSEnabledComponent.tsx, public/pages/Channels/Channels.tsx, public/pages/Emails/components/tables/RecipientGroupsTable.tsx, public/pages/Emails/components/tables/SESSendersTable.tsx, public/pages/Emails/components/tables/SendersTable.tsx
* Manual Backport [PR] (https://github.com/opensearch-project/dashboards-notifications/pull/192)
=> Backport/backport 192 to 2.x

release-notes/opensearch-dashboards-notifications.release-notes-2.14.0.0.md
* Added release notes for 2.14
=> adding release notes for 2.14

opensearch_dashboards.json, public/components/MDSEnabledComponent/MDSEnabledComponent.tsx, public/pages/Main/Main.tsx, public/services/NotificationService.ts
Manual backport PR of https://github.com/opensearch-project/dashboards-notifications/pull/205
=> Backport/backport 205 to 2.x

release-notes/opensearch-dashboards-notifications.release-notes-2.15.0.0.md
=> release-notes added for 2.15

opensearch_dashboards.json, public/pages/Main/Main.tsx
This PR filters out the versions which are not supported when MDS support is enabled
=> version decoupling support

opensearch_dashboards.json, public/pages/Main/Main.tsx
Manual Backport PR: version decoupling
=> Backport/backporting to 2.x

release-notes/opensearch-dashboards-notifications.release-notes-2.16.0.0.md
=> added release notes 2.16

README.md, public/plugin.ts
=> [navigation]feat: change parent item name

CONTRIBUTING.md, NOTICE, README.md, public/pages/Channels/__tests__/__snapshots__/DetailsListModal.test.tsx.snap, public/pages/Channels/__tests__/__snapshots__/DetailsTableModal.test.tsx.snap, yarn.lock
Added missing files to fix link checker check
=> Fix link checker

public/pages/Main/Main.tsx, release-notes/opensearch-dashboards-notifications.release-notes-2.17.0.0.md
* Persist dataSourceId across applications under new Nav change
Signed-off-by: Riya Saxena <riysaxen@amazon.com>
* release notes added
Signed-off-by: Riya Saxena <riysaxen@amazon.com>
* release notes added
Signed-off-by: Riya Saxena <riysaxen@amazon.com>
* release notes added
Signed-off-by: Riya Saxena <riysaxen@amazon.com>
* release notes added
Signed-off-by: Riya Saxena <riysaxen@amazon.com>
* release notes added
Signed-off-by: Riya Saxena <riysaxen@amazon.com>
---------
Signed-off-by: Riya Saxena <riysaxen@amazon.com>
Signed-off-by: Riya <69919272+riysaxen-amzn@users.noreply.github.com>
(cherry picked from commit 774f9ab78eda7d83c8698d75f36578473ccafd4e)
By submitting this pull request, I confirm that my …
=> [Backport 2.x] Release notes 2.17(#248)

public/pages/Main/Main.tsx, release-notes/opensearch-dashboards-notifications.release-notes-2.17.0.0.md
* Persist dataSourceId across applications under new Nav change
Signed-off-by: Riya Saxena <riysaxen@amazon.com>
* release notes added
Signed-off-by: Riya Saxena <riysaxen@amazon.com>
* release notes added
Signed-off-by: Riya Saxena <riysaxen@amazon.com>
* release notes added
Signed-off-by: Riya Saxena <riysaxen@amazon.com>
* release notes added
Signed-off-by: Riya Saxena <riysaxen@amazon.com>
* release notes added
Signed-off-by: Riya Saxena <riysaxen@amazon.com>
---------
Signed-off-by: Riya Saxena <riysaxen@amazon.com>
Signed-off-by: Riya <69919272+riysaxen-amzn@users.noreply.github.com>
(cherry picked from commit 774f9ab78eda7d83c8698d75f36578473ccafd4e)
By submitting this pull request, I confirm that my …
=> [Backport 2.17] Release notes (#248)

public/pages/CreateChannel/CreateChannel.tsx, public/pages/Emails/CreateRecipientGroup.tsx, public/utils/constants.ts
* Breadcrumb added with a name while editing a channel and recepient group page
=> edit page changes as per new page header

.github/workflows/dashboards-notifications-test-and-build-workflow-prod-docker-linux.yml, .github/workflows/dashboards-notifications-test-and-build-workflow.yml
Updated workflows to use latest action of upload-artifacts
=> Updated workflows to use latest action of upload-artifacts

opensearch_dashboards.json, package.json
- Incremented version to 2.18.0-SNAPSHOT.
=> Increment version to 2.18.0.0

release-notes/opensearch-dashboards-notifications.release-notes-2.18.0.0.md
Added 2.18.0 release notes.
https://github.com/opensearch-project/dashboards-notifications/issues/262
=> Added 2.18.0 release notes.

public/pages/Main/Main.tsx
This PR fixes the edge cases for datasource selection when it could have invalid semver.
=> [Multi datasource] Update order of validation; catch exceptions in semver check

package.json, yarn.lock
Bumped cypress version to 12.17.4.
=> Bumped cypress version to 12.17.4.

release-notes/opensearch-dashboards-notifications.release-notes-2.19.0.0.md
Added 2.19 release notes.
https://github.com/opensearch-project/dashboards-notifications/issues/294
=> Added 2.19 release notes.

release-notes/opensearch-dashboards-notifications.release-notes-3.0.0.0-alpha1.md
Added 3.0-alpha1 release notes.
https://github.com/opensearch-project/dashboards-notifications/issues/87
=> Added 3.0-alpha1 release notes.

.github/workflows/dashboards-notifications-test-and-build-workflow-prod-docker-linux.yml, .github/workflows/dashboards-notifications-test-and-build-workflow.yml, .github/workflows/verify-binary-installation.yml, opensearch_dashboards.json, package.json
Update version qualifier to beta1.
https://github.com/opensearch-project/dashboards-notifications/issues/87
=> Update version qualifier to beta1.

release-notes/opensearch-dashboards-notifications.release-notes-3.0.0.0-beta1.md
Added 3.0-beta1 release notes.
https://github.com/opensearch-project/dashboards-notifications/issues/87
=> Added 3.0-beta1 release notes.

package.json, yarn.lock
Bumped cypress version.
https://github.com/opensearch-project/dashboards-notifications/issues/305
=> Bumped cypress version.
